language: node_js
node_js:
  - "stable"

cache:
  directory:
    - node_modules

addons:
  apt:
    update: true
    packages:
      - node-semver

before_install: true

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run test

# before_cache:
after_success:
  - git config --local user.name "Commitplay CI-CD Worker"
  - git config --local user.name "ci-cd@commitplay.io"
  - CURRENT_VERSION=$(node -p "require('./package.json').version")
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      echo "on master branch";
      export TRAVIS_TAG=v$CURRENT_VERSION-release;
    fi;
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then
      echo "on develop branch";
      PREV_RC=$(git tag -l "v$CURRENT_VERSION-rc*" | tail -1);
      if [ $PREV_RC ]; then
        export TRAVIS_TAG=v$(semver $PREV_RC -i prerelease --preid rc);
      else
        export TRAVIS_TAG=v$(semver $CURRENT_VERSION-rc.1);
      fi;
    fi;
  - echo "Version $TRAVIS_TAG is tagged"


# after_failure:

before_deploy:
  - npm run package-mac
  - npm run package-linux
  - tar czf builds/commitplay-tools-app-darwin-x64.tar.gz builds/commitplay-tools-app-darwin-x64
  - tar czf builds/commitplay-tools-app-linux-x64.tar.gz builds/commitplay-tools-app-linux-x64

# The api key is generated by james-lim@github.com
deploy:
  - provider: releases
    api_key:
      secure: rk1ehUmQPjYe2Ppqmbsp7N/nMgjsWpbtR4/gfutImzVMCIE3g663qKKgYNHGZTqY9kYlnQPjZ8ZUNJg9FAeiUSgp9Yg7eemDs+OqvXV0brnEl6YZLNABqvKaTsQeQNk1qU+rv2hXRvGqmPeFxvXZVUr4B6fS1ot9gz+x+lhl0xhmCiO/tgpJ7WTXBoFh8vSSMWyP9puhogij1BR/pigHqOrbbmtSaXQNv83dFzTiZkOKJYOF1Z9CTriLQd0RUYtCFVUJMaaI5e/t/vdtIbPWIq8ewMzDQoUeYTN2HmyRqbprJys7uqqSMAg0tjNypUdc8DK5ERQne9LHABfNlHzlG5J458ZSMzIV8XMLrE6Cs+ndV8gO5S1noVeHSh61es79O5KgLH5mqBr3TUIENOMOSpCFdnd4Sl6R0mq8hhrbPuOD/SkDtVOWVoumDgVTxQlC4cELNIkK8ymvSc7kfHcS71TJsUrpoplFJvb6H8YqAER3F+d9Jmc1XVA7o8eaQ7jWFb6HBuDA+GKqUJKDNbhv5WMAumdtcw+7PMhdHEfxMso/wyWBvm7ygkLF6aUutCRn4zvFNaVakb6XA+FOpQVi+gDDayXy45vZXpqScQk9O1iykZLXl8OrL3BRN6h93PfYQoIxGPz5QmtWVJou2QXKyBjVi9TgY7Ba2za+v4wq77s=
    file:
      - builds/commitplay-tools-app-darwin-x64.tar.gz
      - builds/commitplay-tools-app-linux-x64.tar.gz
    skip_cleanup: true
    overwrite: true
    on:
      branch: master
      repo: commitplay/commitplay-work-tools
      tags: true
  - provider: releases
    api_key:
      secure: rk1ehUmQPjYe2Ppqmbsp7N/nMgjsWpbtR4/gfutImzVMCIE3g663qKKgYNHGZTqY9kYlnQPjZ8ZUNJg9FAeiUSgp9Yg7eemDs+OqvXV0brnEl6YZLNABqvKaTsQeQNk1qU+rv2hXRvGqmPeFxvXZVUr4B6fS1ot9gz+x+lhl0xhmCiO/tgpJ7WTXBoFh8vSSMWyP9puhogij1BR/pigHqOrbbmtSaXQNv83dFzTiZkOKJYOF1Z9CTriLQd0RUYtCFVUJMaaI5e/t/vdtIbPWIq8ewMzDQoUeYTN2HmyRqbprJys7uqqSMAg0tjNypUdc8DK5ERQne9LHABfNlHzlG5J458ZSMzIV8XMLrE6Cs+ndV8gO5S1noVeHSh61es79O5KgLH5mqBr3TUIENOMOSpCFdnd4Sl6R0mq8hhrbPuOD/SkDtVOWVoumDgVTxQlC4cELNIkK8ymvSc7kfHcS71TJsUrpoplFJvb6H8YqAER3F+d9Jmc1XVA7o8eaQ7jWFb6HBuDA+GKqUJKDNbhv5WMAumdtcw+7PMhdHEfxMso/wyWBvm7ygkLF6aUutCRn4zvFNaVakb6XA+FOpQVi+gDDayXy45vZXpqScQk9O1iykZLXl8OrL3BRN6h93PfYQoIxGPz5QmtWVJou2QXKyBjVi9TgY7Ba2za+v4wq77s=
    file:
      - builds/commitplay-tools-app-darwin-x64.tar.gz
      - builds/commitplay-tools-app-linux-x64.tar.gz
    skip_cleanup: true
    overwrite: true
    prerelease: true
    on:
      branch: develop
      repo: commitplay/commitplay-work-tools
      tags: true

# after_deploy:
# after_script:
